name: CI

on:
  - push
  - pull_request

jobs:
  test:
    name: Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 16
        os:
          - ubuntu-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@master
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: pnpm install --no-frozen-lockfile
      - run: npm run build
      - run: npm run test
